[package]
name = "otii_measurement"
version = "0.1.1"
authors = ["Sebastian Andersson <sebastian@bittr.nu>"]
edition = "2021"
rust-version = "1.70.0"

[dependencies]
clap = { version = "4.*", features = ["derive"] }
serial = "0.4.*"
indicatif = "0.17.*"
ctrlc = "3.4.*"
